### ISSUE TITLE
If coarsened is false in config, printed config in output file includes a number of bins that is wrong

### ISSUE THREAD

**Issue by cpatel-seii** [JohnEFerguson/project-reserve#156]
<img width="1440" alt="Screen Shot 2020-12-24 at 9 50 54 AM" src="https://user-images.githubusercontent.com/65291323/103095134-86604380-45cd-11eb-9293-74389ad559b8.png">

If the coarsened status in the config is set to false, the printed number of bins should say 1

**Comment by cpatel-seii** [comment]
@sgrund14 This is fixed - thank you! One minor follow-up re this: is it possible to in the print_config code add an if statement to print ``number_of_bins`` as 0 if ``coarsened`` == FALSE? Right now it is printing the internal number of bins which might be confusing to a user (see cell C13 below)

![image](https://user-images.githubusercontent.com/65291323/104933428-e650cc80-5976-11eb-87c6-4518582a3f36.png)

**Comment by sgrund14** [comment]
this should have also been fixed on the latest master, are we sure you are using the right build? i thought this was the original problem (except the solution was to print number_of_bins as 1, not 0)

https://github.com/JohnEFerguson/project-reserve/blob/e9e4d1f32521ffd626942fa3e345dd3859d1ade6/src/public/pages/reserve-instances.vue#L275-L277

this is saying if it's coarsened, print the real number of bins, otherwise print just 1 bin. we can change it 0 easily, but I suspect you are using an old build

**Comment by cpatel-seii** [comment]
Ya @sgrund14 damn I think I am - sorry about that, printing 1 works perfectly

**Comment by cpatel-seii** [comment]
Looks good @sgrund14 - thanks!
